server:
  port: 8080

spring:
  application:
    name: ShoeShelf

  datasource:
    url: jdbc:postgresql://localhost:5432/shoeshelf_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345
    hikari:
      maximum-pool-size: 10
      auto-commit: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true