server:
  port: 8080

spring:
  application:
    name: ShoeShelf

  datasource:
    url: jdbc:postgresql://localhost:5432/shoeshelf_db
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
    hikari:
      maximum-pool-size: 10
      auto-commit: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true

  # Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

security:
  auth:
    user: admin
    password: Pass@12345
    role: ADMIN

cors:
  allowed-origins:
    - http://localhost:5173